#!/usr/bin/env node
/* One-off: recompute the historical odds-history entries for the days when the
 * Round of 32 was already drawn, using the current projection engine — which now
 * follows FIFA's FIXED bracket (data/bracket.js) instead of randomly re-pairing
 * knockout survivors. Only entries whose snapshot has the bracket set are
 * touched (playedMatches >= the 72 group games); earlier group-stage entries are
 * left exactly as they were (the engine reproduces the old random-pairing path
 * there anyway, so re-running would only add sim noise).
 *
 * Each day's titleOdds / meanPts / avgFinish are re-derived by replaying the
 * SAME engine against the data/matches.js blob as it existed that day, pulled
 * from git by matching played-match count (same technique as
 * backfill_avg_finish.js).
 *
 *     node scripts/backfill_bracket.js [nSims]
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { simulate, avgFinishOf, ALL_MATCHES, MANAGERS, hasResult } = require("./build_projections.js");

const ROOT = path.resolve(__dirname, "..");
const N = Number(process.argv[2]) || 20000;
const HIST = path.join(ROOT, "data/odds_history.js");
const MIN_PLAYED = 72; // group stage complete → Round of 32 is drawn

function parseMatches(src) { const window = {}; eval(src); return window.MATCHES || []; }

let history;
{ const window = {}; eval(fs.readFileSync(HIST, "utf8")); history = window.ODDS_HISTORY; }

const commits = execSync(`git log --format=%H%x09%cI -- data/matches.js`, { cwd: ROOT })
  .toString().trim().split("\n").map((l) => { const [hash, iso] = l.split("\t"); return { hash, iso, date: iso.slice(0, 10) }; });

const blobCache = new Map();
function blobFor(hash) {
  if (!blobCache.has(hash)) {
    let m; try { m = parseMatches(execSync(`git show ${hash}:data/matches.js`, { cwd: ROOT }).toString()); } catch (e) { m = null; }
    blobCache.set(hash, m);
  }
  return blobCache.get(hash);
}
const playedCount = (m) => (m ? m.filter(hasResult).length : -1);

// The matches.js blob with exactly entry.playedMatches results, most recent on/
// before the entry date (so fixtures announced that day are included).
function reconstruct(entry) {
  let exact = null, nearest = null, nearestGap = Infinity;
  for (const c of commits.filter((c) => c.date <= entry.date)) {
    const m = blobFor(c.hash); if (!m) continue;
    const pc = playedCount(m);
    if (pc === entry.playedMatches) { exact = { c, m, pc }; break; }
    const gap = Math.abs(pc - entry.playedMatches);
    if (gap < nearestGap) { nearestGap = gap; nearest = { c, m, pc }; }
  }
  return exact || nearest;
}

const ordered = MANAGERS.slice();
console.log(`Recomputing R32-era entries (playedMatches >= ${MIN_PLAYED}) at ${N} sims each:\n`);
console.log("date        played  source(commit/played)         leader P(1st)");

for (const entry of history) {
  if (entry.playedMatches < MIN_PLAYED) continue; // leave group-stage entries untouched
  const isToday = entry === history[history.length - 1];
  let matches, srcLabel;
  if (isToday) { matches = ALL_MATCHES; srcLabel = `working-tree/${playedCount(ALL_MATCHES)}`; }
  else {
    const r = reconstruct(entry);
    if (!r) { console.warn(`  ${entry.date}: no matches.js blob found — skipped`); continue; }
    matches = r.m; srcLabel = `${r.c.hash.slice(0, 7)}/${r.pc}${r.pc === entry.playedMatches ? "" : "*approx"}`;
  }

  const { managersOut } = simulate(matches, N);
  const byName = {}; for (const m of managersOut) byName[m.name] = m;
  // keep the established stable key order (best mean first), as the daily build writes it
  const order = ordered.slice().sort((a, b) => byName[b].mean - byName[a].mean);
  entry.titleOdds = {}; entry.meanPts = {}; entry.avgFinish = {};
  for (const name of order) {
    entry.titleOdds[name] = byName[name].finish[0];
    entry.meanPts[name] = byName[name].mean;
    entry.avgFinish[name] = avgFinishOf(byName[name].finish);
  }
  const lead = order.reduce((a, b) => (entry.titleOdds[b] > entry.titleOdds[a] ? b : a), order[0]);
  console.log(`${entry.date}   ${String(entry.playedMatches).padStart(3)}     ${srcLabel.padEnd(28)}  ${lead} ${(entry.titleOdds[lead] * 100).toFixed(1)}%`);
}

history.sort((a, b) => String(a.date).localeCompare(String(b.date)));
fs.writeFileSync(HIST,
  `// AUTO-GENERATED by scripts/build_projections.js — daily title-odds history.\n` +
  `window.ODDS_HISTORY = ` + JSON.stringify(history, null, 1) + ";\n");
console.log(`\nWrote data/odds_history.js — ${history.length} entries (R32-era recomputed with the fixed bracket).`);
