#!/usr/bin/env node
/* Recompute the ENTIRE odds-history series (titleOdds / meanPts / avgFinish) for
 * every day through the current projection engine, so methodology changes apply
 * retroactively to the beginning of the tournament. Covers:
 *   - FIFA's fixed knockout bracket once the R32 is drawn (data/bracket.js)
 *   - Kyle's daily draft-mistake bonus (build_projections KYLE_BONUS)
 *
 * Each day is replayed against the data/matches.js blob as it existed that day,
 * pulled from git by matching played-match count (the most fixture-complete such
 * commit on/before the entry date). Today's entry uses the working tree.
 *
 *     node scripts/backfill_history.js [nSims]
 */
"use strict";
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { simulate, avgFinishOf, ALL_MATCHES, MANAGERS, hasResult } = require("./build_projections.js");

const ROOT = path.resolve(__dirname, "..");
const N = Number(process.argv[2]) || 20000;
const HIST = path.join(ROOT, "data/odds_history.js");

function parseMatches(src) { const window = {}; eval(src); return window.MATCHES || []; }

let history;
{ const window = {}; eval(fs.readFileSync(HIST, "utf8")); history = window.ODDS_HISTORY; }

const commits = execSync(`git log --format=%H%x09%cI -- data/matches.js`, { cwd: ROOT })
  .toString().trim().split("\n").map((l) => { const [hash, iso] = l.split("\t"); return { hash, iso, date: iso.slice(0, 10) }; });

const blobCache = new Map();
function blobFor(hash) {
  if (!blobCache.has(hash)) {
    let m; try { m = parseMatches(execSync(`git show ${hash}:data/matches.js`, { cwd: ROOT }).toString()); } catch (e) { m = null; }
    blobCache.set(hash, m);
  }
  return blobCache.get(hash);
}
const playedCount = (m) => (m ? m.filter(hasResult).length : -1);

function reconstruct(entry) {
  let exact = null, nearest = null, nearestGap = Infinity;
  for (const c of commits.filter((c) => c.date <= entry.date)) {
    const m = blobFor(c.hash); if (!m) continue;
    const pc = playedCount(m);
    if (pc === entry.playedMatches) { exact = { c, m, pc }; break; }
    const gap = Math.abs(pc - entry.playedMatches);
    if (gap < nearestGap) { nearestGap = gap; nearest = { c, m, pc }; }
  }
  return exact || nearest;
}

console.log(`Recomputing the full ${history.length}-day history at ${N} sims each:\n`);
console.log("date        played  source(commit/played)        leader  Kyle P(1st)");

for (const entry of history) {
  const isToday = entry === history[history.length - 1];
  let matches, srcLabel;
  if (isToday) { matches = ALL_MATCHES; srcLabel = `working-tree/${playedCount(ALL_MATCHES)}`; }
  else {
    const r = reconstruct(entry);
    if (!r) { console.warn(`  ${entry.date}: no matches.js blob found — skipped`); continue; }
    matches = r.m; srcLabel = `${r.c.hash.slice(0, 7)}/${r.pc}${r.pc === entry.playedMatches ? "" : "*approx"}`;
  }

  const { managersOut } = simulate(matches, N);
  const byName = {}; for (const m of managersOut) byName[m.name] = m;
  const order = MANAGERS.slice().sort((a, b) => byName[b].mean - byName[a].mean);
  entry.titleOdds = {}; entry.meanPts = {}; entry.avgFinish = {};
  for (const name of order) {
    entry.titleOdds[name] = byName[name].finish[0];
    entry.meanPts[name] = byName[name].mean;
    entry.avgFinish[name] = avgFinishOf(byName[name].finish);
  }
  const lead = order.reduce((a, b) => (entry.titleOdds[b] > entry.titleOdds[a] ? b : a), order[0]);
  console.log(`${entry.date}   ${String(entry.playedMatches).padStart(3)}     ${srcLabel.padEnd(28)}  ${lead.padEnd(7)} ${(entry.titleOdds.KYLE * 100).toFixed(1)}%`);
}

history.sort((a, b) => String(a.date).localeCompare(String(b.date)));
fs.writeFileSync(HIST,
  `// AUTO-GENERATED by scripts/build_projections.js — daily title-odds history.\n` +
  `window.ODDS_HISTORY = ` + JSON.stringify(history, null, 1) + ";\n");
console.log(`\nWrote data/odds_history.js — full ${history.length}-day series recomputed (fixed bracket + Kyle's daily bonus).`);
